---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewew-c824f56d
  labels:
    app: ewew-c824f56d
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ewew-c824f56d
  template:
    metadata:
      labels:
        app: ewew-c824f56d
    spec:
      containers:
        - name: ewew-c824f56d
          image: docker.io/phengbunath/ewew-c824f56d:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
