---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ewew-c824f56d                  # Ingress name
  labels:
    app: ewew-c824f56d
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "ewew-c824f56d.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ewew-c824f56d               # Links to Service name dynamically
                port:
                  number: 8080  # Links to service port dynamically
